#!/bin/bash

if which node < /dev/null then goto noNode

if which npm < /dev/null then goto noNpm

clear

cd ..
cd ..
npm install

:noNode
clear
echo
echo NodeJs NOT installed.
echo NodeJs is required.
echo Your browser will open and navigate to the NodaJS download page in 30 seconds.
echo If you want to find it yourself just close the installer now.
echo Press Enter to open download page now.
read -t 35

xdg-open https://nodejs.org/en/download/ & > /dev/null

exit

:noNpm
clear
echo
echo There seems to be something wrong with your NodeJS install.
echo npm was not found. You may want to reinstall NodeJS.
echo
pause

exit

